parameters:
  name: null
  additionalOptions: null
  internalProjectName: null
  publicProjectName: null
  
jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: $(defaultLinuxAmd64PoolImage)
  variables:
    internalProjectName: ${{ parameters.internalProjectName }}
    publicProjectName: ${{ parameters.publicProjectName }}
  steps:
  - template: ../steps/init-docker-linux.yml
  - ${{ if eq(variables['System.TeamProject'], variables.publicProjectName) }}:
    - template: ../steps/set-dry-run.yml
  - script: >
      $(runImageBuilderCmd)
      copyBaseImages
      '$(acr.servicePrincipalName)'
      '$(acr.servicePrincipalPassword)'
      '$(acr.servicePrincipalTenant)'
      '$(acr.subscription)'
      '$(acr.resourceGroup)'
      $(mirrorRegistryCreds)
      --repo-prefix $(mirrorRepoPrefix)
      --registry-override '$(acr.server)'
      --os-type 'linux'
      --architecture '*'
      $DRYRUNARG
      ${{ parameters.additionalOptions }}
    displayName: Copy Base Images
    continueOnError: true
  - template: ../steps/cleanup-docker-linux.yml
