parameters:
  name: null
  pool: {}
  matrix: {}
  testJobTimeout: 60
  internalProjectName: null
  publicProjectName: null
jobs:
- job: ${{ parameters.name }}
  condition: and(succeeded(), ${{ parameters.matrix }})
  dependsOn: GenerateTestMatrix
  pool: ${{ parameters.pool }}
  strategy:
    matrix: $[ ${{ parameters.matrix }} ]
  timeoutInMinutes: ${{ parameters.testJobTimeout }}
  variables:
    internalProjectName: ${{ parameters.internalProjectName }}
    publicProjectName: ${{ parameters.publicProjectName }}
  steps:
  - template: ../steps/test-images-windows-client.yml
