trigger:
  batch: true
  branches:
    include:
    - nightly
  paths:
    include:
    - manifest.json
    - manifest.versions.json
    - src/*
pr: none

resources:
  repositories:
  - repository: InternalVersionsRepo
    type: git
    name: internal/dotnet-versions

variables:
- template: variables/core.yml
- name: internalProjectName
  value: internal
- name: officialBranches
  value: "'nightly'"

stages:
- template: ../common/templates/stages/build-test-publish-repo.yml
  parameters:
    testMatrixCustomBuildLegGroupArgs: --custom-build-leg-group test-dependencies
